# fly.toml app configuration file generated for mlb-live-scores on 2026-04-07T03:04:51Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "mlb-live-scores"
primary_region = "iad"

[env]
PORT = "8080"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
